config/routes.rb
Rails.application.routes.draw do

  root    'welcome#index'
  get     'signin'  => 'sessions#new'
  post    'signin'  => 'sessions#create'
  get     'signup'  => 'users#new'
  delete  'signout' => 'sessions#destroy'
  
  resources :users
  resources :sports

end

app/models/User.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  before_save { email.downcase! }
  
  has_many :sports
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  belongs_to :user
  
  validates_presence_of :user_id, required: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'session'
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:email].downcase)
      if user && user.authenticate(params[:password])
        sign_in user
        redirect_to user
      else
        flash.now[:error] = 'Invalid email/password combination'
        render 'new'
      end
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :signed_in_user, execpt: [:show]
  
  def index
  end
  
  def new
    @sport = Sport.new
  end
  
  def create
    @sport = Sport.new(sport_params)
    @sport.user_id = current_user.id
    if @sport.save
      flash[:success] = "You have now created your sport!"
      redirect_to @sport
    else
      render 'new'
    end
  end
  
  def show
    @sport = Sport.find(params[:id])
  end
  
  def edit
    @sport = Sport.find(params[:id])
  end
  
  def update
    @sport = Sport.find(params[:id])
    if @sport.update_attributes(sport_params)
      flash[:success] = "Sport Information successfully updated!"
      redirect_to @sport
    else
      render 'edit'
    end
  end
  
  private
  
    def sport_params
      params.require(:sport).permit(:name, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'signup', only: [:new]
  before_action :signed_in_user, only: [:edit, :update, :destroy]
   
  def new
    @user = User.new
  end
  
  def edit
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the League Tracker!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def update
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def destroy
  end
  
    private
  
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_sports_list
    return @sports = current_user.sports if defined?(current_user)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def signed_in_user
    unless signed_in?
      redirect_to signin_path, notice: "Please Sign in."
    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeagueTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="PageContainer">
    <%= render 'shared/navigation' %>

    <div class='main_content'>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeagueTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class='main-content'>
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeagueTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class='main-content'>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<% if signed_in? %>
  <nav class="side_nav">
    <div class="nav-profile">
      <ul>
        <li class="current_player">
          <img></img>
          <h3><%= current_user.name %></h3>
          <a><%= link_to "Edit Profile", edit_user_path(current_user)%> </a>
        </li>
      </ul>
    </div>
    <div class="nav_sports">
      <ul>
        <% current_user.sports.each do |sport|%>
        <li><%= link_to sport.name, sport_path(sport) unless blank? %></li>
        <% end %>
        <li><%= link_to "Create New Sport", new_sport_path %></li>
      </ul>
    </div>
    
    <div class="nav_footer">
      <ul>
        <li><%= link_to "Sign out", signout_path, method: :delete %></li>
      </ul>
    </div>
  </nav>
<% else %>
  <nav class="top_nav">
      <h1>League Tracker</h1>
    <ul>
      <li><%= link_to "Sign in", signin_path %></li>
      <li><%= link_to "Create new Account", new_user_path %></li>
    </ul>
  </nav>
<% end %>

app/views/sports/_fields.html.erb
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_field :description %>

app/views/sports/edit.html.erb
<%= form_for(@sport) do |f| %>
<%= render partial: 'fields', locals: { f: f } %>
<%= f.submit "Update" %>
<% end %>

<%= link_to 'back to sport', sport_path(@sport)%>

app/views/sports/new.html.erb
<%= form_for(@sport) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit "Create Sport!" %>

<% end %>

app/views/sports/show.html.erb
<header>
  <h1><%= @sport.name %></h1>
  <h2><%= @sport.description unless blank? %></h2>
</header>

<div class="toolbar">
  <%= link_to "+ Add a result" %>
  <%= link_to "Invite a Player" %>
  <%= link_to "Settings", edit_sport_path(@sport) %>
</div>

app/views/users/new.html.erb
<%= link_to "<back", root_path %>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>
  <hr>
	<%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<header>
  <h1>Personal Profile</h1>
</header>